// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbedbnqzepkgjpmmyldt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiZWRibnF6ZXBrZ2pwbW15bGR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODk0NzUsImV4cCI6MjA2Njg2NTQ3NX0.0x7UP4UdaUle7LQr8wpMnxGI7TUCExES-8gkFt_BwNQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);